spring.application.name=eventapp

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5467/eventapp}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
spring.datasource.username=${DATABASE_USERNAME:eventapp}
spring.datasource.password=${DATABASE_PASSWORD:eventapp123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

security.jwt.secret=${JWT_SECRET:eventapp-super-secret-key-eventapp-super-secret-key-123456}
security.jwt.expiration-ms=86400000

external.nominatim.base-url=https://nominatim.openstreetmap.org
external.nominatim.user-agent=EventAppBAWEB/1.0 (szbudzinski@gmail.com)
