spring.application.name=eventapp

spring.datasource.url=jdbc:postgresql://localhost:5467/eventapp
spring.datasource.username=eventapp
spring.datasource.password=eventapp123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

server.port=8080
security.jwt.secret=eventapp-super-secret-key-eventapp-super-secret-key-123456
security.jwt.expiration-ms=86400000

external.nominatim.base-url=https://nominatim.openstreetmap.org
external.nominatim.user-agent=EventAppBAWEB/1.0 (szbudzinski@gmail.com)